name: "CI (Atualização Api-Dev-epsoft): GitAction"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  java-teste: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Verificação Simples
        run: echo "Tudo certo com o setup inicial."

  deploy-api:
    runs-on: ubuntu-latest
    environment:
      name: api
    needs: java-teste
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Parar o Container Existente
        run: |
          ssh -i ${{ secrets.KEY_SECRETORIGINAL }} ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} -p ${{ vars.REMOTE_PORT }} << 'EOF'
          docker ps -q --filter "name=Api_atividades_dev" | grep -q . && docker stop Api_atividades_dev
          EOF

      - name: Substituir o Arquivo .jar
        run: |
          scp -i ${{ secrets.KEY_SECRETORIGINAL }} -P ${{ vars.REMOTE_PORT }} /home/ubuntu/volumes/homologacao/api/analytics.jar ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}:/home/ubuntu/volumes/homologacao/api

      - name: Iniciar o Container com Novo .jar
        run: |
          ssh -i ${{ secrets.KEY_SECRETORIGINAL }} ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} -p ${{ vars.REMOTE_PORT }} << 'EOF'
          docker start Api_atividades_dev
          EOF
