name: "CI (Atualização Api-Dev): GitAction"

on:
  # Ativa o workflow em push ou pull request na branch main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  java-teste: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Verificação Simples
        run: echo "Tudo certo com o setup inicial."

  deploy-api:
    runs-on: ubuntu-latest
    environment:
      name: api
    needs: java-teste
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Deploy da API
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.KEY_SECRETORIGINAL }}
          # Define os argumentos adicionais do rsync, se necessário
          # ARGS: "-rlgoDzvc --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
